baseURL = 'https://spsseano.com/'
languageCode = 'en-us'
title = "Sean's Shitposting"

theme = "pure"
lastmod = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

copyright = 2024

[permalinks]
  [permalinks.page]
    posts = '/p/:year/:month/:slug/'
    guides = '/g/:slug'
    links = '/l/:slug'
  [permalinks.section]
    posts = '/posts/'
    guides = '/guides/'
    links = '/links/'

[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  style = 'solarized-light'
  lineNos = true

[frontmatter]
  date = ["publish", ":default"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
  description = "working thru the pain"
  lastmod = true
  headerIcon = "/images/octicon.png"
  avatar = "/images/avatar.png"

[[params.links]]
  type = "link"
  override = "octoface"
  link = "github.com/spslater/shitposting"
  display = "github repo"
[[params.links]]
  type = "email"
  link = "sean@spslater.com"
[[params.links]]
  type = "link"
  link = "leagueofcomicgeeks.com/profile/spsseano"
  display = "League of Comic Geeks"
[[params.links]]
  type = "link"
  override = "book"
  link = "https://www.goodreads.com/_sean"
  display = "Goodreads"

[[params.socials]]
  site = "tumblr"
  value = "feelin.blue"
  vanity = true
[[params.socials]]
  site = "bluesky"
  value = "spsseano.com"
